### ISSUE TITLE
Cannot see the provider added in the list

### ISSUE THREAD

**Issue by simistef** [clinton-hall/couchpotato.provider.quorks#4]
Hi there,

I have couchpotato version:

Version 5b1dd686 (17 Jan 2015 14:04:58 EET)
Updater git, masterID12701
Directories
/usr/local/couchpotatoserver/share/CouchPotatoServer
/usr/local/couchpotatoserver/var
Startup Args
['--daemon', '--pid_file', '/usr/local/couchpotatoserver/var/couchpotatoserver.pid', '--config_file', '/usr/local/couchpotatoserver/var/settings.conf']Namespace(config_file='/usr/local/couchpotatoserver/var/settings.conf', console_log=False, daemon=True, data_dir=None, debug=False, pid_file='/usr/local/couchpotatoserver/var/couchpotatoserver.pid', quiet=False)

I have copied the files inside the folder /usr/local/couchpotatoserver/var/quorks but it does not appear on the torrent provider list. The logs are empty and do not show any errors ?

Any idea what i can do to make this work ?

Thanks!

**Comment by clinton-hall** [comment]
you need to put the scripts in /usr/local/couchpotatoserver/var/custom_plugins/quorks/

Then the provider should appear.... but I belive this provider is no longer runing (last I heard the site shutdown).
